defmodule TestFleet.Accounts do
  @moduledoc """
  Users, sessions, invitations, and roles.

  Generated by `mix phx.gen.auth` and adapted: there is no open registration.
  The first admin is created by the first-run setup, everyone else is invited.
  Only active users can log in: invited users first accept their invitation,
  deactivated users not at all.
  """

  import Ecto.Query, warn: false
  alias TestFleet.Repo

  alias TestFleet.Accounts.{APIToken, OIDC, Scope, User, UserIdentity, UserToken, UserNotifier}
  alias TestFleet.Notifications
  alias TestFleet.Organizations
  alias TestFleet.Organizations.{Membership, Organization}

  require Logger

  @setup_token_key {__MODULE__, :setup_token}

  ## Database getters

  @doc """
  Gets a user by email.

  ## Examples

      iex> get_user_by_email("foo@example.com")
      %User{}

      iex> get_user_by_email("unknown@example.com")
      nil

  """
  def get_user_by_email(email) when is_binary(email) do
    Repo.get_by(User, email: email)
  end

  @doc """
  Gets an active user by email and password.

  ## Examples

      iex> get_user_by_email_and_password("foo@example.com", "correct_password")
      %User{}

      iex> get_user_by_email_and_password("foo@example.com", "invalid_password")
      nil

  """
  def get_user_by_email_and_password(email, password)
      when is_binary(email) and is_binary(password) do
    user = Repo.get_by(User, email: email)
    if User.valid_password?(user, password) and User.active?(user), do: user
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Gets a member of the scope's organization with their OIDC identities, API token
  count there, and role there, for the Members page. Raises `Ecto.NoResultsError`
  for a user who is not a member.
  """
  def get_member!(%Scope{organization: %Organization{} = organization}, id) do
    from(u in User, where: u.id == ^id, preload: :identities)
    |> with_api_token_count(organization)
    |> with_role(organization)
    |> Repo.one!()
  end

  @doc """
  The scope's organization's members, by email, with their OIDC identities, API
  token counts there, and roles there.
  """
  def list_members(%Scope{organization: %Organization{} = organization}) do
    from(u in User, order_by: u.email, preload: :identities)
    |> with_api_token_count(organization)
    |> with_role(organization)
    |> Repo.all()
  end

  # Members only: the join drops everyone else.
  defp with_role(query, %Organization{id: organization_id}) do
    from u in query,
      join: m in Membership,
      on: m.user_id == u.id and m.organization_id == ^organization_id,
      select_merge: %{role: m.role}
  end

  defp with_api_token_count(query, %Organization{id: organization_id}) do
    counts =
      from t in APIToken,
        where: t.organization_id == ^organization_id,
        group_by: t.user_id,
        select: %{user_id: t.user_id, count: count(t.id)}

    from u in query,
      left_join: c in subquery(counts),
      on: c.user_id == u.id,
      select_merge: %{api_token_count: coalesce(c.count, 0)}
  end

  @doc "Whether emailed invitations and email changes can be sent (SMTP is configured)."
  def email_enabled?, do: Notifications.email_configured?()

  @doc """
  Whether password login is available (`AUTH_PASSWORD_LOGIN`). Off means
  "SSO button only": no password or magic-link login.
  """
  def password_login_enabled?,
    do: Application.get_env(:testfleet, __MODULE__, [])[:password_login] != false

  @doc "Whether magic links can be used: password login is available and SMTP is configured."
  def magic_link_enabled?, do: password_login_enabled?() and email_enabled?()

  ## First-run setup

  @doc """
  The one-time token of the first-run setup: random, in memory only,
  and new on every start. The application generates it when it starts.
  """
  def setup_token do
    case :persistent_term.get(@setup_token_key, nil) do
      nil ->
        token = 24 |> :crypto.strong_rand_bytes() |> Base.url_encode64(padding: false)
        :persistent_term.put(@setup_token_key, token)
        token

      token ->
        token
    end
  end

  @doc "Whether the first-run setup creates the organization (there is none yet)."
  def setup_creates_organization?,
    do: not Organizations.multi?() and is_nil(Organizations.single())

  @doc "Whether the setup is still open (there is no user yet)."
  def setup_needed?, do: not Repo.exists?(User)

  @doc "Whether `token` is the setup token and the setup is still open."
  def valid_setup_token?(token) when is_binary(token) do
    Plug.Crypto.secure_compare(token, setup_token()) and setup_needed?()
  end

  def valid_setup_token?(_token), do: false

  @doc "Returns an `%Ecto.Changeset{}` for the setup form (the password is not hashed)."
  def change_setup(attrs \\ %{}) do
    User.setup_changeset(%User{}, attrs, hash_password: false)
  end

  @doc """
  Creates the first admin, if there is no user yet, and the organization, unless
  it exists already (an installation from before organizations). Two concurrent
  setups create one admin: the other gets `{:error, :already_set_up}`.
  """
  def create_first_admin(attrs) do
    Repo.transact(fn ->
      lock(:setup)

      if setup_needed?() do
        changeset = User.setup_changeset(%User{}, attrs)
        name = Ecto.Changeset.get_field(changeset, :organization_name)

        with {:ok, user} <- Repo.insert(changeset),
             {:ok, _} <- join_first_organization(user, name) do
          {:ok, user}
        else
          {:error, %Ecto.Changeset{data: %Organization{}} = org_changeset} ->
            {:error, organization_error(changeset, org_changeset)}

          error ->
            error
        end
      else
        {:error, :already_set_up}
      end
    end)
  end

  defp join_first_organization(user, name \\ nil) do
    with {:ok, organization} <- first_organization(name) do
      Organizations.put_membership(user, organization, :admin)
    end
  end

  # An installation from before organizations already has one.
  defp first_organization(name) do
    case Organizations.single() do
      nil ->
        Organizations.create_organization(%{
          name: if(name in [nil, ""], do: "Default", else: name)
        })

      organization ->
        {:ok, organization}
    end
  end

  # The organization's name is invalid, e.g. its slug is reserved: shown on the setup form.
  defp organization_error(changeset, org_changeset) do
    message =
      case org_changeset.errors do
        [{:slug, {msg, _}} | _] ->
          slug = Ecto.Changeset.get_field(org_changeset, :slug)
          ~s(gives the URL name "#{slug}", which #{msg}; choose another name)

        [{_field, {msg, _}} | _] ->
          msg
      end

    changeset
    |> Ecto.Changeset.add_error(:organization_name, message)
    |> Map.put(:action, :insert)
  end

  ## Invitations

  @doc "Returns an `%Ecto.Changeset{}` for the invitation form."
  def change_invitation(attrs \\ %{}) do
    User.invite_changeset(%User{}, attrs, validate_unique: false)
  end

  @doc """
  Invites a user by email and role into the scope's organization. Returns the
  link, to be shown to the admin once; with SMTP, it is also emailed.

      {:ok, %{user: user, url: url, emailed?: boolean}}
  """
  def invite_user(%Scope{organization: %Organization{} = organization}, attrs, url_fun)
      when is_function(url_fun, 1) do
    Repo.transact(fn ->
      with {:ok, user} <- %User{} |> User.invite_changeset(attrs) |> Repo.insert(),
           {:ok, _} <- Organizations.put_membership(user, organization, user.role) do
        {:ok, {user, insert_invite_token(user)}}
      end
    end)
    |> deliver_invitation(url_fun)
  end

  @doc """
  Creates a new link for a pending invitation; the old one stops working.
  """
  def renew_invitation(%User{} = user, url_fun) when is_function(url_fun, 1) do
    if User.status(user) == :invited do
      Repo.transact(fn ->
        Repo.delete_all(
          from(t in UserToken, where: t.user_id == ^user.id and t.context == "invite")
        )

        {:ok, {user, insert_invite_token(user)}}
      end)
      |> deliver_invitation(url_fun)
    else
      {:error, :not_invited}
    end
  end

  @doc "Revokes a pending invitation. The invited user is deleted: nothing refers to it."
  def revoke_invitation(%User{} = user) do
    if User.status(user) == :invited, do: Repo.delete(user), else: {:error, :not_invited}
  end

  defp insert_invite_token(user) do
    {encoded_token, user_token} = UserToken.build_email_token(user, "invite")
    Repo.insert!(user_token)
    encoded_token
  end

  defp deliver_invitation({:ok, {user, token}}, url_fun) do
    url = url_fun.(token)
    {:ok, %{user: user, url: url, emailed?: email_enabled?() and emailed?(user, url)}}
  end

  defp deliver_invitation(error, _url_fun), do: error

  defp emailed?(user, url) do
    case UserNotifier.deliver_invitation(user, url) do
      {:ok, _email} ->
        true

      {:error, reason} ->
        Logger.warning("Could not email the invitation for user #{user.id}: #{inspect(reason)}")
        false
    end
  end

  @doc "Gets the user of a valid invitation token, or nil."
  def get_user_by_invitation_token(token) do
    with {:ok, query} <- UserToken.verify_invite_token_query(token) do
      Repo.one(query)
    else
      _ -> nil
    end
  end

  @doc """
  Accepts an invitation: sets the password and confirms the user. All of the user's
  tokens are deleted, the invitation among them.

      {:ok, {user, expired_tokens}} | {:error, :invalid_token} | {:error, changeset}
  """
  def accept_invitation(token, attrs) do
    case get_user_by_invitation_token(token) do
      nil ->
        {:error, :invalid_token}

      user ->
        user
        |> User.password_changeset(attrs)
        |> then(&if(user.confirmed_at, do: &1, else: User.confirm_changeset(&1)))
        |> update_user_and_delete_all_tokens()
    end
  end

  @doc """
  Makes `email` an active admin, creating the user if needed, and returns a link
  that sets a new password: for a lost admin account.
  """
  def invite_admin(email, url_fun) when is_binary(email) and is_function(url_fun, 1) do
    Repo.transact(fn ->
      result =
        case get_user_by_email(email) do
          nil ->
            %User{} |> User.invite_changeset(%{email: email}) |> Repo.insert()

          user ->
            user |> Ecto.Changeset.change(deactivated_at: nil) |> Repo.update()
        end

      with {:ok, user} <- result,
           {:ok, _} <- Organizations.put_membership(user, Organizations.single!(), :admin) do
        Repo.delete_all(
          from(t in UserToken, where: t.user_id == ^user.id and t.context == "invite")
        )

        {:ok, url_fun.(insert_invite_token(user))}
      end
    end)
  end

  ## OIDC

  @doc "The user's identity at the configured provider, or nil."
  def get_identity(%User{id: user_id}) do
    Repo.get_by(UserIdentity, user_id: user_id, issuer: OIDC.issuer())
  end

  @doc """
  Logs in with a provider identity (`login` mode):

  1. a known identity logs its user in, unless deactivated;
  2. an unknown identity whose email the provider verified is linked to the user
     with that email (confirming a pending invitation);
  3. an unknown identity without a user gets a member account, if provisioning is
     on and the email's domain is allowed;
  4. an unknown identity whose email matches a user but is not verified is refused.

      {:ok, user}
      | {:error, :deactivated | :email_not_verified | :not_invited | :domain_not_allowed}
  """
  def oidc_login(identity) do
    Repo.transact(fn ->
      case find_identity(identity) do
        %UserIdentity{user: user} = found ->
          if User.status(user) == :deactivated do
            {:error, :deactivated}
          else
            Repo.update_all(from(i in UserIdentity, where: i.id == ^found.id),
              set: [email: identity.email]
            )

            {:ok, user}
          end

        nil ->
          case get_user_by_email(identity.email) do
            nil -> provision(identity)
            user -> link_by_email(user, identity)
          end
      end
    end)
  end

  defp find_identity(%{issuer: issuer, subject: subject}) do
    Repo.one(
      from i in UserIdentity,
        where: i.issuer == ^issuer and i.subject == ^subject,
        preload: :user
    )
  end

  defp link_by_email(user, identity) do
    cond do
      User.status(user) == :deactivated ->
        {:error, :deactivated}

      identity.email_verified ->
        with {:ok, _} <- insert_identity(user, identity), do: confirm(user)

      true ->
        {:error, :email_not_verified}
    end
  end

  defp provision(identity) do
    cond do
      not OIDC.provisioning?() ->
        {:error, :not_invited}

      not OIDC.allowed_domain?(identity.email) ->
        {:error, :domain_not_allowed}

      true ->
        with {:ok, user} <- insert_confirmed(identity.email),
             {:ok, _} <- join_provisioned(user),
             {:ok, _} <- insert_identity(user, identity) do
          {:ok, user}
        end
    end
  end

  @doc """
  Creates the first admin with a provider identity (`setup` mode), if there is
  still no user.
  """
  def oidc_setup(identity) do
    Repo.transact(fn ->
      lock(:setup)

      if setup_needed?() do
        with {:ok, user} <- insert_confirmed(identity.email),
             {:ok, _} <- join_first_organization(user),
             {:ok, _} <- insert_identity(user, identity) do
          {:ok, user}
        end
      else
        {:error, :already_set_up}
      end
    end)
  end

  @doc """
  Accepts an invitation with a provider identity (`invite` mode): the link is the
  authorization, so the provider need not verify the email. Like
  `accept_invitation/2`, all of the user's tokens are deleted.

      {:ok, {user, expired_tokens}} | {:error, :invalid_token | :identity_taken}
  """
  def oidc_accept_invitation(token, identity) do
    case get_user_by_invitation_token(token) do
      nil ->
        {:error, :invalid_token}

      user ->
        Repo.transact(fn ->
          with {:ok, _} <- replace_identity(user, identity) do
            user
            |> Ecto.Changeset.change(confirmed_at: user.confirmed_at || DateTime.utc_now(:second))
            |> update_user_and_delete_all_tokens()
          end
        end)
    end
  end

  @doc """
  Links a provider identity to a logged-in user (`link` mode, from the settings),
  replacing an earlier one.

      {:ok, identity} | {:error, :identity_taken}
  """
  def link_identity(%User{} = user, identity) do
    Repo.transact(fn -> replace_identity(user, identity) end)
  end

  @doc """
  Unlinks the provider, while another way in remains (a password with password
  login available, or magic links): otherwise `{:error, :last_login_method}`.
  """
  def unlink_identity(%User{} = user) do
    if can_unlink?(user) do
      {count, _} =
        Repo.delete_all(
          from i in UserIdentity, where: i.user_id == ^user.id and i.issuer == ^OIDC.issuer()
        )

      {:ok, count}
    else
      {:error, :last_login_method}
    end
  end

  @doc "Whether the user keeps a way in without the provider."
  def can_unlink?(%User{} = user) do
    (password_login_enabled?() and not is_nil(user.hashed_password)) or magic_link_enabled?()
  end

  # In :multi mode a provisioned user belongs to no organization yet.
  defp join_provisioned(user) do
    if Organizations.multi?(),
      do: {:ok, nil},
      else: Organizations.put_membership(user, Organizations.single!(), :member)
  end

  defp insert_confirmed(email) do
    %User{}
    |> User.invite_changeset(%{email: email})
    |> User.confirm_changeset()
    |> Repo.insert()
  end

  defp confirm(%User{confirmed_at: nil} = user) do
    Repo.delete_all(from(t in UserToken, where: t.user_id == ^user.id and t.context == "invite"))
    user |> User.confirm_changeset() |> Repo.update()
  end

  defp confirm(user), do: {:ok, user}

  defp replace_identity(user, identity) do
    Repo.delete_all(
      from i in UserIdentity, where: i.user_id == ^user.id and i.issuer == ^identity.issuer
    )

    insert_identity(user, identity)
  end

  defp insert_identity(user, identity) do
    %UserIdentity{user_id: user.id}
    |> UserIdentity.changeset(identity)
    |> Repo.insert()
    |> case do
      {:ok, identity} -> {:ok, identity}
      {:error, %Ecto.Changeset{}} -> {:error, :identity_taken}
    end
  end

  ## API tokens

  # Polling pipelines would otherwise write on every request.
  @last_used_interval_seconds 5 * 60

  @doc "The scope's user's API tokens, of all their organizations, newest first."
  def list_api_tokens(%Scope{user: %User{id: user_id}}) do
    Repo.all(
      from t in APIToken,
        where: t.user_id == ^user_id,
        order_by: [desc: t.id],
        preload: :organization
    )
  end

  @doc "Returns an `%Ecto.Changeset{}` for the new-token form."
  def change_api_token(attrs \\ %{}), do: APIToken.changeset(%APIToken{}, attrs)

  @doc """
  Creates an API token for the scope's user, in the scope's organization. The
  token is returned once and never stored:

      {:ok, {token, api_token}} | {:error, changeset}
  """
  def create_api_token(
        %Scope{user: %User{} = user, organization: %Organization{} = organization},
        attrs
      ) do
    {token, changeset} =
      %APIToken{user_id: user.id, organization_id: organization.id}
      |> APIToken.changeset(attrs)
      |> APIToken.generate()

    with {:ok, api_token} <- Repo.insert(changeset),
         do: {:ok, {token, %{api_token | organization: organization}}}
  end

  @doc "Revokes one of the scope's user's API tokens. Another user's token is `{:error, :not_found}`."
  def delete_api_token(%Scope{user: %User{id: user_id}}, id) do
    case Repo.delete_all(from t in APIToken, where: t.id == ^id and t.user_id == ^user_id) do
      {1, _} -> :ok
      {0, _} -> {:error, :not_found}
    end
  end

  @doc """
  The scope (the active user, the token's organization, and the membership) and
  the token for an API token, or nil: unknown and expired tokens, deactivated
  users' tokens, and tokens of users who are no longer members are all nil.
  Records the use, at most every #{div(@last_used_interval_seconds, 60)} minutes.
  """
  def get_scope_by_api_token(token, now \\ DateTime.utc_now(:second))

  def get_scope_by_api_token(token, now) when is_binary(token) do
    with true <- APIToken.well_formed?(token),
         %APIToken{user: user, organization: organization} = api_token <-
           Repo.one(
             from t in APIToken,
               where: t.token_hash == ^APIToken.hash(token),
               preload: [:user, :organization]
           ),
         false <- APIToken.expired?(api_token, now),
         true <- User.active?(user),
         %Membership{} = membership <- Organizations.get_membership(user, organization) do
      scope = Scope.put_organization(%Scope{user: user}, organization, membership)
      {scope, touch_api_token(api_token, now)}
    else
      _ -> nil
    end
  end

  def get_scope_by_api_token(_token, _now), do: nil

  defp touch_api_token(%APIToken{last_used_at: last} = api_token, now) do
    if is_nil(last) or DateTime.diff(now, last) >= @last_used_interval_seconds do
      Repo.update_all(from(t in APIToken, where: t.id == ^api_token.id),
        set: [last_used_at: now]
      )

      %{api_token | last_used_at: now}
    else
      api_token
    end
  end

  ## Roles and deactivation

  @doc """
  Changes a member's role in the scope's organization. The organization's last
  active admin cannot be demoted: `{:error, :last_admin}`.
  """
  def update_user_role(
        %Scope{organization: %Organization{} = organization},
        %User{} = user,
        role
      )
      when role in [:admin, :member] do
    Repo.transact(fn ->
      if role == :member and last_active_admin?(user, organization) do
        {:error, :last_admin}
      else
        with {:ok, _membership} <- Organizations.put_membership(user, organization, role) do
          {:ok, %{user | role: role}}
        end
      end
    end)
  end

  @doc """
  Deactivates a user, account-wide: login is refused and all tokens are deleted,
  API tokens included. Returns the deleted session tokens, so their LiveViews can
  be disconnected. An organization's last active admin cannot be deactivated:
  `{:error, :last_admin}`.
  """
  def deactivate_user(%User{} = user) do
    Repo.transact(fn ->
      if last_active_admin_anywhere?(user) do
        {:error, :last_admin}
      else
        Repo.delete_all(from t in APIToken, where: t.user_id == ^user.id)

        user
        |> Ecto.Changeset.change(deactivated_at: DateTime.utc_now(:second))
        |> update_user_and_delete_all_tokens()
      end
    end)
  end

  @doc """
  Removes a member from the scope's organization (`:multi` mode; in `:single`
  mode, deactivate instead): deletes the membership and the user's API tokens of
  that organization. Returns the user's session tokens, so their pages can be
  disconnected. The organization's last active admin cannot be removed:
  `{:error, :last_admin}`.
  """
  def remove_member(
        %Scope{organization: %Organization{id: organization_id} = organization},
        %User{} = user
      ) do
    Repo.transact(fn ->
      if last_active_admin?(user, organization) do
        {:error, :last_admin}
      else
        Repo.delete_all(
          from m in Membership,
            where: m.user_id == ^user.id and m.organization_id == ^organization_id
        )

        Repo.delete_all(
          from t in APIToken,
            where: t.user_id == ^user.id and t.organization_id == ^organization_id
        )

        {:ok,
         Repo.all(from t in UserToken, where: t.user_id == ^user.id and t.context == "session")}
      end
    end)
  end

  @doc "Reactivates a deactivated user."
  def reactivate_user(%User{} = user) do
    user |> Ecto.Changeset.change(deactivated_at: nil) |> Repo.update()
  end

  # Inside a transaction: locks the admins, so two admins cannot demote each other
  # at the same time.
  defp last_active_admin?(%User{} = user, %Organization{id: organization_id}) do
    lock(:admins)
    last_active_admin_in?(user, organization_id)
  end

  defp last_active_admin_anywhere?(%User{id: user_id} = user) do
    lock(:admins)

    from(m in Membership,
      where: m.user_id == ^user_id and m.role == :admin,
      select: m.organization_id
    )
    |> Repo.all()
    |> Enum.any?(&last_active_admin_in?(user, &1))
  end

  defp last_active_admin_in?(%User{id: user_id} = user, organization_id) do
    admin? =
      Repo.exists?(
        from m in Membership,
          where:
            m.user_id == ^user_id and m.organization_id == ^organization_id and
              m.role == :admin
      )

    admin? and User.active?(user) and
      not Repo.exists?(
        from m in Membership,
          join: u in assoc(m, :user),
          where:
            m.organization_id == ^organization_id and m.role == :admin and
              u.id != ^user_id and is_nil(u.deactivated_at) and not is_nil(u.confirmed_at)
      )
  end

  defp lock(name) do
    Repo.query!("SELECT pg_advisory_xact_lock(hashtext($1))", ["testfleet.accounts.#{name}"])
  end

  @doc "Records a login, shown on the Users page."
  def record_login(%User{id: id}) do
    Repo.update_all(from(u in User, where: u.id == ^id),
      set: [last_login_at: DateTime.utc_now(:second)]
    )

    :ok
  end

  ## Settings

  @doc """
  Checks whether the user is in sudo mode.

  The user is in sudo mode when the last authentication was done no further
  than 20 minutes ago. The limit can be given as second argument in minutes.
  """
  def sudo_mode?(user, minutes \\ -20)

  def sudo_mode?(%User{authenticated_at: ts}, minutes) when is_struct(ts, DateTime) do
    DateTime.after?(ts, DateTime.utc_now() |> DateTime.add(minutes, :minute))
  end

  def sudo_mode?(_user, _minutes), do: false

  @doc """
  Returns an `%Ecto.Changeset{}` for changing the user email.

  See `TestFleet.Accounts.User.email_changeset/3` for a list of supported options.

  ## Examples

      iex> change_user_email(user)
      %Ecto.Changeset{data: %User{}}

  """
  def change_user_email(user, attrs \\ %{}, opts \\ []) do
    User.email_changeset(user, attrs, opts)
  end

  @doc """
  Updates the user email using the given token.

  If the token matches, the user email is updated and the token is deleted.
  """
  def update_user_email(user, token) do
    context = "change:#{user.email}"

    Repo.transact(fn ->
      with {:ok, query} <- UserToken.verify_change_email_token_query(token, context),
           %UserToken{sent_to: email} <- Repo.one(query),
           {:ok, user} <- Repo.update(User.email_changeset(user, %{email: email})),
           {_count, _result} <-
             Repo.delete_all(from(UserToken, where: [user_id: ^user.id, context: ^context])) do
        {:ok, user}
      else
        _ -> {:error, :transaction_aborted}
      end
    end)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for changing the user password.

  See `TestFleet.Accounts.User.password_changeset/3` for a list of supported options.

  ## Examples

      iex> change_user_password(user)
      %Ecto.Changeset{data: %User{}}

  """
  def change_user_password(user, attrs \\ %{}, opts \\ []) do
    User.password_changeset(user, attrs, opts)
  end

  @doc """
  Updates the user password.

  Returns a tuple with the updated user, as well as a list of expired tokens.

  ## Examples

      iex> update_user_password(user, %{password: ...})
      {:ok, {%User{}, [...]}}

      iex> update_user_password(user, %{password: "too short"})
      {:error, %Ecto.Changeset{}}

  """
  def update_user_password(user, attrs) do
    user
    |> User.password_changeset(attrs)
    |> update_user_and_delete_all_tokens()
  end

  ## Session

  @doc """
  Generates a session token.
  """
  def generate_user_session_token(user) do
    {token, user_token} = UserToken.build_session_token(user)
    Repo.insert!(user_token)
    token
  end

  @doc """
  Gets the user with the given signed token.

  If the token is valid `{user, token_inserted_at}` is returned, otherwise `nil` is returned.
  """
  def get_user_by_session_token(token) do
    {:ok, query} = UserToken.verify_session_token_query(token)
    Repo.one(query)
  end

  @doc """
  Gets the user with the given magic link token.
  """
  def get_user_by_magic_link_token(token) do
    with {:ok, query} <- UserToken.verify_magic_link_token_query(token),
         {user, _token} <- Repo.one(query) do
      user
    else
      _ -> nil
    end
  end

  @doc """
  Logs the user in by magic link.

  Only active users get magic links (the token query checks it again), so the
  generator's confirmation case does not apply: invited users accept their
  invitation instead. The magic link is expired.
  """
  def login_user_by_magic_link(token) do
    with {:ok, query} <- UserToken.verify_magic_link_token_query(token),
         {user, token} <- Repo.one(query) do
      Repo.delete!(token)
      {:ok, {user, []}}
    else
      _ -> {:error, :not_found}
    end
  end

  @doc ~S"""
  Delivers the update email instructions to the given user.

  ## Examples

      iex> deliver_user_update_email_instructions(user, current_email, &url(~p"/users/settings/confirm-email/#{&1}"))
      {:ok, %{to: ..., body: ...}}

  """
  def deliver_user_update_email_instructions(%User{} = user, current_email, update_email_url_fun)
      when is_function(update_email_url_fun, 1) do
    {encoded_token, user_token} = UserToken.build_email_token(user, "change:#{current_email}")

    Repo.insert!(user_token)
    UserNotifier.deliver_update_email_instructions(user, update_email_url_fun.(encoded_token))
  end

  @doc """
  Delivers the magic link login instructions to the given user, if the user is active.
  """
  def deliver_login_instructions(%User{} = user, magic_link_url_fun)
      when is_function(magic_link_url_fun, 1) do
    if User.active?(user) do
      {encoded_token, user_token} = UserToken.build_email_token(user, "login")
      Repo.insert!(user_token)
      UserNotifier.deliver_login_instructions(user, magic_link_url_fun.(encoded_token))
    else
      {:error, :inactive}
    end
  end

  @doc """
  Deletes the signed token with the given context.
  """
  def delete_user_session_token(token) do
    Repo.delete_all(from(UserToken, where: [token: ^token, context: "session"]))
    :ok
  end

  ## Token helper

  defp update_user_and_delete_all_tokens(changeset) do
    Repo.transact(fn ->
      with {:ok, user} <- Repo.update(changeset) do
        tokens_to_expire = Repo.all_by(UserToken, user_id: user.id)

        Repo.delete_all(from(t in UserToken, where: t.id in ^Enum.map(tokens_to_expire, & &1.id)))

        {:ok, {user, tokens_to_expire}}
      end
    end)
  end
end
