defmodule TestFleet.Instance do
  @moduledoc """
  This database's identity. Containers carry it as the
  label `TestFleet.instance`, so the reconciler can tell its own orphans from the
  containers of another database on the same Docker host (dev and test, or staging
  and production).

  The id is generated by the migration and read once, then cached.
  """

  import Ecto.Query, only: [from: 2]

  alias TestFleet.Repo

  @key {__MODULE__, :id}

  @doc "The instance id, a UUID string."
  def id do
    case :persistent_term.get(@key, nil) do
      nil ->
        id = Repo.one!(from i in "instance", select: type(i.id, Ecto.UUID))
        :persistent_term.put(@key, id)
        id

      id ->
        id
    end
  end
end
